### ISSUE TITLE
Including blank "index" column causes workflow to stall 

### ISSUE THREAD

**Issue by allaway** [nf-core/bamtofastq#67]
### Description of the bug

I recently ran this workflow with a samplesheet that included the `index` column, but I had no index files, so I left this column blank. I did this because I interpreted that this would be required from the: 

> The samplesheet can have as many columns as you desire, however, there is a strict requirement for the first 3 columns to match those defined in the table below. If the index files are not available, the files will be automatically indexed during the pipeline run which can have an effect on the runtime.

Did not work: [ega_samplesheet.csv](https://github.com/nf-core/bamtofastq/files/12897806/ega_samplesheet.csv)
Did work: [foo.csv](https://github.com/nf-core/bamtofastq/files/12897807/foo.csv)

When I tried to run the workflow with the first samplesheet, it seemed to stall right at the beginning, and none of the actual workflow processes started: 

```
N E X T F L O W  ~  version 23.04.2
Pulling nf-core/bamtofastq ...
downloaded from https://github.com/nf-core/bamtofastq.git
Launching `https://github.com/nf-core/bamtofastq` [elated_laplace] DSL2 - revision: c70f49b20c [2.1.0]
Downloading plugin nf-validation@1.0.0
WARN: The following invalid input values have been detected:
* --cpus: 4
* --single_cpu_mem: 6 GB
```
<img width="476" alt="Screen Shot 2023-10-13 at 2 08 37 PM" src="https://github.com/nf-core/bamtofastq/assets/20408008/a8da5eb6-018b-41d7-bcfb-a10993e9018b">

It's quite possible that this is an issue specific to our environment, and not reproducible when running locally - I'm not sure. However, I think if the docs were changed: 

> The samplesheet can have as many columns as you desire, however, there is a strict requirement for the first 3 columns to match those defined in the table below. If the index files are not available, the files will be automatically indexed during the pipeline run which can have an effect on the runtime.
to 
> The samplesheet can have as many columns as you desire, however, there is a strict requirement for the first 2 columns to match those defined in the table below. If the index files are not available, the files will be automatically indexed during the pipeline run which can have an effect on the runtime.

Then that might prevent this issue for others (at least, others at my organization 😄  ) in the future. 

### Command used and terminal output

```console
nextflow run 'https://github.com/nf-core/bamtofastq'
		 -name sick_feynman
		 -params-file 'https://tower.sagebionetworks.org/api/ephemeral/lZaLUuTnixmwA_P3fPQHew.yaml'
		 -with-tower 'https://tower.sagebionetworks.org/api'
		 -r 2.1.0
```

### System information

nextflow version: 23.04.2 build 5870
hardware: cloud (aws)
executor:  awsbatch
container engine: docker (i think...)
bamtofastq version: 2.1.0

**Comment by asp8200** [comment]
It seems to me that this issue was resolve satisfactorily by #68. Feel free to otherwise reopen the issue.
